CREATE DATABASE IF NOT EXISTS neueapp_db CHARACTER SET utf8 COLLATE utf8_general_ci;
 
USE neueapp_db;
 
CREATE TABLE IF NOT EXISTS neueapp_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);
